# Generated by Django 3.0.6 on 2020-05-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonDivisors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.IntegerField(max_length=10)),
                ('number2', models.IntegerField(max_length=10)),
                ('number1_divisors', models.TextField(editable=False)),
                ('number2_divisors', models.TextField(editable=False)),
                ('least_greatest_c_divisors', models.TextField(editable=False)),
            ],
        ),
    ]
