# Generated by Django 3.0.6 on 2020-05-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondivisors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondivisors',
            name='number1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commondivisors',
            name='number2',
            field=models.IntegerField(),
        ),
    ]
