# Generated by Django 3.0.6 on 2020-05-18 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commondivisors', '0002_auto_20200518_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commondivisors',
            name='least_greatest_c_divisors',
        ),
        migrations.RemoveField(
            model_name='commondivisors',
            name='number1_divisors',
        ),
        migrations.RemoveField(
            model_name='commondivisors',
            name='number2_divisors',
        ),
    ]
