# Generated by Django 3.0.6 on 2020-05-19 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commondivisors', '0003_auto_20200518_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonDivisors',
            new_name='TwoNumbers',
        ),
    ]
