# Generated by Django 3.0.6 on 2020-05-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondivisors', '0007_auto_20200519_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twonumbers',
            name='number1',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='twonumbers',
            name='number2',
            field=models.PositiveIntegerField(),
        ),
    ]
