# Generated by Django 3.0.6 on 2020-05-23 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondivisors', '0008_auto_20200519_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twonumbers',
            name='number1',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='twonumbers',
            name='number2',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(3)]),
        ),
    ]
