# Generated by Django 3.0.6 on 2020-05-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondivisors', '0009_auto_20200522_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twonumbers',
            name='number1',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='twonumbers',
            name='number2',
            field=models.PositiveIntegerField(),
        ),
    ]
