# Generated by Django 3.0.6 on 2020-05-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondivisors', '0010_auto_20200523_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='twonumbers',
            name='lcd_and_gcd',
            field=models.CharField(default='Missing data', max_length=50),
        ),
        migrations.AddField(
            model_name='twonumbers',
            name='user',
            field=models.CharField(default='Anonymous User', max_length=50),
        ),
    ]
